### PR TITLE
reset content each time we call video.watermark

### PR DESCRIPTION
**Pull request by Cylix**
Hi,

I'm currently using your plugin with the videoJS-playLists plugin and I sometimes need to update the watermark.

However, each time we call `video.watermark({ ... })`, it does not clean the previous content but add the new content over the previous one.

With this commit we can do:

```js
// at first
video.watermark({
  file: 'http://www.videojs.com/img/logo.png',
  xpos: 50,
  ypos: 50,
  xrepeat: 0,
  opacity: 0.5
  });

// then later
video.watermark({
  file: 'http://www.videojs.com/img/an_other_logo.png',
  xpos: 50,
  ypos: 50,
  xrepeat: 0,
  opacity: 0.5
  });
```

This will remove the first content and replace it with the new one.

### CODE REVIEW

**Comment by xbgmsharp** [comment]
Great.
Coud you make the div className an parameter?

**Comment by Cylix** [comment]
Yes of course, I'll do that.

**Comment by Cylix** [comment]
Done, className can now be passed as parameter. Default value is still `vjs-watermark`.

**Comment by xbgmsharp** [comment]
Cool thanks for your commit

**Pull request merged**
